grades:
  - threshold: 92
    label: "отлично"
  - threshold: 75
    label: "хорошо"
  - threshold: 61
    label: "удовлетворительно"
  - threshold: 0
    label: "неудовлетворительно"

test_path: "test/philosophy/questions.yaml"
test_count: 30
result_delay: "500ms"